"""Actividad de clase 15

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10hzlWbsPTo611lXQIBJ2cPBaVN9s047s

**Actividad 14:** Construcción de programas que manipulan archivos

5/octubre/2021

Jaime Eduardo López Castro **A00833173**

Link: https://colab.research.google.com/drive/10hzlWbsPTo611lXQIBJ2cPBaVN9s047s?usp=sharing

### Problema 1
Crea dos matrices 'A' y 'B' de 3 X 3 con datos del 1 al 9 e imprime sus valores renglón por renglón.
"""

a = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
    ]

b = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
    ]

print("Lista A:")
for renglon in a:
  print(renglon)

print("\nLista B:")
for renglon in b:
  print(renglon)

print("\nLista A renglón por renglón:")
for renglon in a:
  for dato in renglon:
    print(dato)

print("\nLista B renglón por renglón:")
for renglon in b:
  for dato in renglon:
    print(dato)

"""### Problema 2
Crea una función que reciba matriz A y sume todos sus elementos e imprima el total.
"""

def sumar_elementos(a):

  suma = 0
  for renglon in a:
    for dato in renglon:
      suma += dato
  
  return suma

a = [
     [5, 2, 3],
     [4, 5, 6],
     [7, 8, 81],
    ]

print(sumar_elementos(a))

"""### Problema 3
Crea una función llamada suma que reciba las matrices A y B matrices y además crea una matriz 'C' que consista en la suma elemento por elemento de las matrices A y B (es decir  C = A + B).
"""

def suma_matriz(a, b):
  c = []

  for line in range(len(a)):
    renglon = []
    for dato in range(len(a[0])):
      suma = a[line][dato] + b[line][dato]
      renglon.append(suma)

    c.append(renglon)
  return c 


a = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
    ]

b = [
     [1, 2, 3],
     [4, 5, 6],
     [7, 8, 9],
    ]

c = suma_matriz(a, b)

print(f"Lista A: {a} \nLista B: {b} \nLista C: {c}")
