"""Actividad de clase 13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15Kt83Ubd2MIyMEhJOmsExJ_GxVDajpZp

**Actividad en clase 13:** Programas con datos estructurados Strings

28/septiembre/2021

Jaime Eduardo López Castro **A00833173**

Link: https://colab.research.google.com/drive/15Kt83Ubd2MIyMEhJOmsExJ_GxVDajpZp?usp=sharing

### Problema 1
Escribe una función que reciba como parámetro una cadena de texto y como resultado devuelva la cadena, pero invertida y en mayúsculas.

cadena = "Esta cadena de texto será invertida"
"""

