# -*- coding: utf-8 -*-
"""Actividad de clase 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DJ-x8kx1MQlh9UK19ra25qJyQGBv21_k

**Actividad 11:** Construcción de programas que utilizan listas

21/septiembre/2021

Jaime Eduardo López Castro **A00833173**

Link: https://colab.research.google.com/drive/1DJ-x8kx1MQlh9UK19ra25qJyQGBv21_k?usp=sharing

### Problema 1
Crea una lista que almancene tu matrícula, nombre y apellido y carrera. Imprime cada uno de los datos en una línea diferente.
"""

# Problema 1

datos = ["A00833173", "Jaime Eduardo", "López", "ITC"]

print(datos[0])
print(datos[1])
print(datos[2])
print(datos[3])

"""### Problema 2
Crea una lista con el nombre de 3 personas. Imprime cada elemento de la lista mediante un ciclo for.
"""

# Problema 2

nombres = ["Ana", "Juan", "Pedro"]

for nombre in nombres:
  print(nombre)

"""### Problema 3
Crea un programa donde el usuario pueda introducir mediante el teclado nombres de 3 libros, los cuales deberás ir guardando en una lista. Al final, imprime la lista de libros.
"""

# Problema 3

libros = []

libros.append(input("Ingresa el primer libro: "))
libros.append(input("Ingresa el segundo libro: "))
libros.append(input("Ingresa el tercer libro: "))

print(libros)

"""### Problema 4
Crea una lista que simule las calificaciones de 10 actividades de un alumno. Supón que debido al excepcional desempeño del alumno, el profesor ha decidido aumentar 5 puntos. Tu programa deberá aumentar a cada calificación los 5 puntos (recordando que la calificación máxima es de 100 y no puede pasarse).
"""

